#!/bin/bash

cd /genetic_algorithm/sat_solvers/minisat_master
make config prefix = $PREFIX
make install

alias zchaff="/genetic_algorithm/sat_solvers/zchaff/zchaff"

alias manysat = "/genetic_algorithm/sat_solvers/manysat2.0/manysat"



