version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      
    working_directory: ~/Gen_Algorithm_TFG
    
    steps:
      # Step 1: obtain repo from Github
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      # Step 3: run coverage and tests
      - run:
        name: run tests
        command: |
          . venv/bin/activate
          python3 -m unittest discover -v -s test/
